"use client";

import { useState } from "react";
import type { FormEvent } from "react";
import { Mail } from "lucide-react";
import type { AbandonedCart, CampaignDraft, NewsletterSubscriber } from "@/lib/admin-data";

const money=(n:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(n);

export default function AdminEmailMarketing({initialSubscribers,initialCampaigns,initialCarts}:{initialSubscribers:NewsletterSubscriber[];initialCampaigns:CampaignDraft[];initialCarts:AbandonedCart[]}) {
  const [tab,setTab]=useState<"Audiencia"|"Campañas"|"Carritos">("Audiencia");
  const [subscribers,setSubscribers]=useState(initialSubscribers); const [campaigns,setCampaigns]=useState(initialCampaigns); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function createCampaign(event:FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement=event.currentTarget; setBusy(true); setMessage(""); const form=new FormData(formElement); const response=await fetch("/api/admin/email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),kind:form.get("kind"),subject:form.get("subject"),preheader:form.get("preheader"),body:form.get("body")})}); const result=await response.json(); setBusy(false); if(!response.ok){setMessage(result.error||"No se pudo guardar.");return;} setCampaigns(current=>[result.campaign,...current]); formElement.reset(); setMessage("Campaña guardada como borrador."); }
  async function toggleSubscriber(subscriber:NewsletterSubscriber) { const response=await fetch("/api/admin/email",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({subscriberId:subscriber.id,active:!subscriber.active})});const result=await response.json();if(!response.ok){setMessage(result.error||"No se pudo actualizar.");return;}setSubscribers(current=>current.map(item=>item.id===result.subscriber.id?result.subscriber:item)); }
  function exportAudience(){const rows=[["correo","nombre","consentimiento"],...subscribers.filter(s=>s.active).map(s=>[s.email,s.name,s.consentedAt])];const csv=rows.map(row=>row.map(value=>`"${value.replaceAll('"','""')}"`).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="el-divan-suscriptores.csv";anchor.click();URL.revokeObjectURL(url);}
  return <><div className="admin-heading"><div><p className="admin-eyebrow">RELACIÓN CON CLIENTES</p><h1 className="editorial-serif">Correos y campañas</h1><p className="admin-muted">Administra consentimientos y prepara comunicaciones de la tienda.</p></div></div><div className="admin-email-note"><Mail size={18}/><span><b>Envíos desactivados</b><small>Las campañas se guardan como borrador. Conecta un proveedor de correo para programar o enviar mensajes.</small></span></div><div className="admin-tabs">{(["Audiencia","Campañas","Carritos"] as const).map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}{item==="Audiencia"?` (${subscribers.filter(s=>s.active).length})`:item==="Campañas"?` (${campaigns.length})`: ` (${initialCarts.filter(c=>c.status==="abierto").length})`}</button>)}</div>{message&&<p className="admin-email-message" role="status">{message}</p>}
  {tab==="Audiencia"&&<section className="admin-panel"><div className="admin-panel-title"><div><h2>Suscriptores del boletín</h2><p>Solo contactos con consentimiento explícito pueden recibir promociones.</p></div><button className="admin-secondary" onClick={exportAudience}>Exportar CSV</button></div>{subscribers.length?<div className="admin-email-list">{subscribers.map(s=><div key={s.id}><span><b>{s.name||"Sin nombre"}</b><small>{s.email} · Consentimiento: {new Date(s.consentedAt).toLocaleDateString("es-MX")}</small></span><button className={`admin-pill ${s.active?"green":"gray"}`} onClick={()=>toggleSubscriber(s)}>{s.active?"Activa · dar de baja":"Inactiva · reactivar"}</button></div>)}</div>:<p className="admin-empty">Aún no hay suscriptores. La lista se llenará con el formulario de la tienda.</p>}</section>}
  {tab==="Campañas"&&<div className="admin-email-grid"><section className="admin-panel admin-email-compose"><div className="admin-panel-title"><div><h2>Nueva campaña</h2><p>El contenido se guardará sin enviarse.</p></div></div><form onSubmit={createCampaign}><label>Nombre interno<input name="name" required maxLength={100} placeholder="Novedades de octubre"/></label><label>Tipo<select name="kind"><option value="novedades">Novedades</option><option value="promocion">Promoción</option><option value="carrito">Recordatorio de carrito</option></select></label><label>Asunto<input name="subject" required maxLength={150}/></label><label>Texto previo<input name="preheader" maxLength={150}/></label><label>Mensaje<textarea name="body" required maxLength={5000} rows={7}/></label><button className="admin-primary" disabled={busy}>{busy?"Guardando…":"Guardar borrador"}</button></form></section><section className="admin-panel"><div className="admin-panel-title"><div><h2>Borradores</h2><p>{campaigns.length} campañas preparadas</p></div></div>{campaigns.length?<div className="admin-email-list">{campaigns.map(c=><div key={c.id}><span><b>{c.name}</b><small>{c.subject} · {c.kind} · {new Date(c.createdAt).toLocaleDateString("es-MX")}</small></span><span className="admin-pill amber">Borrador</span></div>)}</div>:<p className="admin-empty">Todavía no hay campañas.</p>}</section></div>}
  {tab==="Carritos"&&<section className="admin-panel"><div className="admin-panel-title"><div><h2>Actividad de carrito</h2><p>Seguimiento privado de carritos de clientes identificados.</p></div></div>{initialCarts.length?<div className="admin-email-list">{initialCarts.map(cart=><div key={cart.id}><span><b>{cart.customer||cart.email}</b><small>{cart.items.map(item=>`${item.title} × ${item.quantity}`).join(" · ")} · {money(cart.total)} · Actualizado {new Date(cart.updatedAt).toLocaleString("es-MX")}</small></span><span className={`admin-pill ${cart.status==="convertido"?"green":cart.status==="abierto"?"amber":"gray"}`}>{cart.status}</span></div>)}</div>:<p className="admin-empty">Aún no hay carritos registrados. La captura se habilitará cuando exista inicio de sesión para clientes.</p>}</section>}</>;
}
