"use client";

import { useMemo, useState } from "react";
import { BellRing, BookOpen, Boxes, Check, CircleDollarSign, ClipboardList, ExternalLink, FileText, LogOut, Mail, Megaphone, Package, Plus, Search, TicketPercent, Truck, Users, X } from "lucide-react";
import type { AdminCustomer, AdminOrder, ContentPost, OrderStatus, PaymentStatus, PromotionCoupon, RestockRequest, RewardCoupon, SiteSettings, NewsletterSubscriber, CampaignDraft, AbandonedCart } from "@/lib/admin-data";
import AdminPromotions from "@/components/admin-promotions";
import AdminContent from "@/components/admin-content";
import AdminEmailMarketing from "@/components/admin-email-marketing";
import type { Book, ClinicalTopic, LifeStage, TheoreticalOrientation } from "@/lib/types";

type Section = "Resumen" | "Catálogo" | "Pedidos" | "Envíos" | "Clientes" | "Cupones" | "Reposición" | "Promociones" | "Contenido" | "Correos";
const money = (n: number) => new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN", maximumFractionDigits: 0 }).format(n);
const stages: LifeStage[] = ["Prenatal y perinatal", "Bebés y primera infancia", "Infancia", "Adolescencia", "Clínica con adultos", "Pareja y familia", "Envejecimiento y vejez"];
const topics: ClinicalTopic[] = ["Autismo y psicosis infantil", "Psicosis", "Neurosis", "Personalidad, narcisismo y estados límite", "Trauma", "Adicciones y toxicomanías", "Trastornos de la alimentación", "Cuerpo y psicosomática", "Sexualidad y género", "Duelo y pérdida", "Suicidio y autolesiones", "TDAH y problemáticas escolares", "Pareja y familia"];
const orientations: TheoreticalOrientation[] = ["Freud y tradición freudiana", "Melanie Klein y postkleinianos", "Bion y desarrollos bionianos", "Winnicott", "Lacan y orientación lacaniana", "Meltzer", "Psicoanálisis contemporáneo", "Psicoanálisis vincular", "Psicoanálisis francés"];

export default function AdminDashboard({ initialBooks, initialOrders, initialCustomers, restockRequests, initialCoupons, promotionCoupons, siteSettings, posts, initialSubscribers, initialCampaigns, initialCarts }: { initialBooks: Book[]; initialOrders: AdminOrder[]; initialCustomers: AdminCustomer[]; restockRequests: RestockRequest[]; initialCoupons: RewardCoupon[]; promotionCoupons: PromotionCoupon[]; siteSettings: SiteSettings; posts: ContentPost[]; initialSubscribers: NewsletterSubscriber[]; initialCampaigns: CampaignDraft[]; initialCarts: AbandonedCart[] }) {
  const [books, setBooks] = useState(initialBooks);
  const [orders, setOrders] = useState(initialOrders);
  const [section, setSection] = useState<Section>("Resumen");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string | null>(initialOrders[0]?.id || null);
  const [editing, setEditing] = useState<Book | null | undefined>(undefined);
  const [notice, setNotice] = useState("");
  const filteredBooks = useMemo(() => books.filter((book) => `${book.title} ${book.author} ${book.publisher}`.toLowerCase().includes(query.toLowerCase())), [books, query]);
  const filteredOrders = useMemo(() => orders.filter((order) => `${order.id} ${order.customer} ${order.email}`.toLowerCase().includes(query.toLowerCase())), [orders, query]);
  const selectedOrder = orders.find((order) => order.id === selected) || orders[0];
  const pendingShipments = orders.filter((order) => order.status === "Procesando").length;
  const paidTotal = orders.filter((order) => order.paymentStatus === "Pagado").reduce((sum, order) => sum + order.total, 0);

  async function removeBook(book: Book) {
    if (!window.confirm(`¿Eliminar “${book.title}”?`)) return;
    const response = await fetch(`/api/admin/books?id=${encodeURIComponent(book.id)}`, { method: "DELETE" });
    const result = await response.json();
    if (!response.ok) { setNotice(result.error || "No se pudo eliminar la ficha."); return; }
    setBooks((current) => current.filter((item) => item.id !== book.id)); setNotice("Ficha eliminada.");
  }

  async function saveOrder(form: FormData) {
    const payload = { id: String(form.get("id")), status: String(form.get("status")), paymentStatus: String(form.get("paymentStatus")), tracking: String(form.get("tracking")), carrier: String(form.get("carrier")) };
    const response = await fetch("/api/admin/orders", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json();
    if (!response.ok) { setNotice(result.error || "No se pudo actualizar el pedido."); return; }
    setOrders((current) => current.map((order) => order.id === result.order.id ? result.order : order)); setNotice("Pedido y datos de envío actualizados.");
  }

  return <div className="admin-app">
    <aside className="admin-sidebar"><a className="admin-brand" href="/"><span className="admin-brand-symbol">E</span><span><b>EL DIVÁN</b><small>MUNDO PSICOANALÍTICO</small></span></a><div className="admin-side-label">GESTIÓN DE TIENDA</div><nav className="admin-nav">{([ ["Resumen", Boxes], ["Catálogo", BookOpen], ["Pedidos", ClipboardList], ["Envíos", Truck], ["Clientes", Users], ["Cupones", TicketPercent], ["Promociones", Megaphone], ["Contenido", FileText], ["Reposición", BellRing], ["Correos", Mail] ] as const).map(([name, Icon]) => <button key={name} onClick={() => { setSection(name); setNotice(""); }} className={section === name ? "active" : ""}><Icon size={18}/>{name}{name === "Envíos" && pendingShipments > 0 && <span className="admin-nav-count">{pendingShipments}</span>}{name === "Reposición" && restockRequests.length > 0 && <span className="admin-nav-count">{restockRequests.length}</span>}</button>)}</nav><div className="admin-sidebar-bottom"><span className="admin-avatar">AD</span><span className="admin-user-label"><b>Administrador</b><small>Acceso privado</small></span><form action="/api/admin/logout" method="post"><button className="admin-icon-button" title="Cerrar sesión" aria-label="Cerrar sesión"><LogOut size={17}/></button></form></div></aside>
    <main className="admin-main"><header className="admin-topbar"><div><p className="admin-eyebrow">EL DIVÁN / PANEL PRIVADO</p><div className="admin-breadcrumb">Administración <span>/</span> {section}</div></div><a href="/" className="admin-store-link" target="_blank">Ver tienda <ExternalLink size={14}/></a></header>
      <div className="admin-content">{notice && <div className="admin-notice" role="status"><Check size={16}/>{notice}<button onClick={() => setNotice("")}><X size={16}/></button></div>}
        {section === "Resumen" && <><div className="admin-heading"><div><p className="admin-eyebrow">JUEVES, 1 DE OCTUBRE DE 2026</p><h1 className="editorial-serif">Buenos días</h1><p className="admin-muted">Aquí tienes el resumen de tu tienda.</p></div><button className="admin-primary" onClick={() => { setSection("Catálogo"); setEditing(null); }}><Plus size={17}/> Agregar libro</button></div><div className="admin-stat-grid"><Stat icon={ClipboardList} label="Pedidos registrados" value={orders.length.toString()} note={`${orders.filter(o=>o.status === "Pendiente").length} por revisar`}/><Stat icon={CircleDollarSign} label="Ventas cobradas" value={money(paidTotal)} note="En pedidos pagados"/><Stat icon={Package} label="Libros en catálogo" value={books.length.toString()} note={`${books.filter(b=>b.available).length} disponibles`}/><Stat icon={Truck} label="Por preparar" value={pendingShipments.toString()} note="Listos para envío"/></div><section className="admin-panel"><div className="admin-panel-title"><div><h2>Pedidos recientes</h2><p>Actividad más reciente de tu tienda</p></div><button className="admin-text-button" onClick={() => setSection("Pedidos")}>Ver todos →</button></div><OrderTable orders={[...orders].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4)} onSelect={(id)=>{setSelected(id);setSection("Pedidos");}}/></section><div className="admin-two-col"><section className="admin-panel"><div className="admin-panel-title"><div><h2>Inventario</h2><p>Disponibilidad de títulos</p></div><BookOpen size={18}/></div><div className="admin-inventory-row"><span>Disponibles</span><b>{books.filter(b=>b.available).length} títulos</b></div><div className="admin-inventory-bar"><i style={{width:`${books.length ? books.filter(b=>b.available).length / books.length * 100 : 0}%`}}/></div><div className="admin-inventory-row muted"><span>Agotados / ocultos</span><b>{books.filter(b=>!b.available).length} títulos</b></div></section><section className="admin-tip"><span className="admin-tip-icon">✦</span><p className="admin-eyebrow">RECUERDA</p><h3 className="editorial-serif">Una ficha completa ayuda a descubrir cada libro.</h3><button onClick={()=>setSection("Catálogo")}>Administrar catálogo →</button></section></div></>}
        {section === "Correos" && <AdminEmailMarketing initialSubscribers={initialSubscribers} initialCampaigns={initialCampaigns} initialCarts={initialCarts}/>} {section === "Contenido" && <AdminContent initialPosts={posts}/>} {section === "Promociones" && <AdminPromotions initialCoupons={promotionCoupons} initialSettings={siteSettings}/> } {section === "Catálogo" && <><div className="admin-heading"><div><p className="admin-eyebrow">CONTENIDO DE LA TIENDA</p><h1 className="editorial-serif">Catálogo e inventario</h1><p className="admin-muted">Las existencias se reflejan automáticamente en la tienda.</p></div><button className="admin-primary" onClick={()=>setEditing(null)}><Plus size={17}/> Agregar libro</button></div><div className="admin-toolbar"><label className="admin-search"><Search size={17}/><input placeholder="Buscar título, autor o editorial" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><span>{filteredBooks.length} títulos</span></div><section className="admin-panel admin-table-panel"><table className="admin-table"><thead><tr><th>LIBRO</th><th>EDITORIAL</th><th>PRECIO</th><th>EXISTENCIAS</th><th>ESTADO</th><th/></tr></thead><tbody>{filteredBooks.map(book=><tr key={book.id}><td><div className="admin-book-table-title">{book.coverImage?<img src={book.coverImage} alt=""/>:<span className="admin-book-table-placeholder">E</span>}<span><b>{book.title}</b><small>{book.author} · {book.year}</small></span></div></td><td>{book.publisher}</td><td>{money(book.price)}</td><td><b>{book.stock}</b> pzas.</td><td><span className={`admin-pill ${book.stock>0?book.stock<=2?"amber":"green":"gray"}`}><i/> {book.stock>0?book.stock<=2?"Stock bajo":"Disponible":"Agotado"}</span></td><td className="admin-actions"><button onClick={()=>setEditing(book)}>Editar</button><button onClick={()=>removeBook(book)}>Eliminar</button></td></tr>)}</tbody></table>{filteredBooks.length===0&&<p className="admin-empty">No hay libros que coincidan con la búsqueda.</p>}</section></>}
        {(section === "Pedidos" || section === "Envíos") && <><div className="admin-heading"><div><p className="admin-eyebrow">OPERACIÓN DE TIENDA</p><h1 className="editorial-serif">{section}</h1><p className="admin-muted">{section === "Pedidos" ? "Consulta compras, pagos y prepara los siguientes pasos." : "Actualiza paquetería, guía y estado de entrega."}</p></div></div><div className="admin-toolbar"><label className="admin-search"><Search size={17}/><input placeholder="Buscar pedido o cliente" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><span>{filteredOrders.length} pedidos</span></div><div className="admin-orders-layout"><section className="admin-panel admin-order-list"><OrderTable orders={section === "Envíos" ? filteredOrders.filter(o=>o.status === "Procesando" || o.status === "Enviado" || o.status === "Entregado") : filteredOrders} onSelect={setSelected} selected={selectedOrder?.id}/></section>{selectedOrder ? <OrderDetail key={selectedOrder.id} order={selectedOrder} onSave={saveOrder}/> : <section className="admin-panel admin-empty">No hay pedidos para mostrar.</section>}</div></>}
        {section === "Clientes" && <><div className="admin-heading"><div><p className="admin-eyebrow">RELACIÓN CON CLIENTES</p><h1 className="editorial-serif">Clientes y recompensas</h1><p className="admin-muted">Historial basado en pedidos completados. Cada cinco libros entregados desbloquean 10%.</p></div></div><div className="admin-toolbar"><label className="admin-search"><Search size={17}/><input placeholder="Buscar cliente o correo" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><span>{initialCustomers.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(query.toLowerCase())).length} clientes</span></div><section className="admin-panel admin-table-panel"><table className="admin-table"><thead><tr><th>CLIENTE</th><th>PEDIDOS</th><th>LIBROS ENTREGADOS</th><th>RECOMPENSA</th><th>CUPONES</th></tr></thead><tbody>{initialCustomers.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(query.toLowerCase())).map(customer=><tr key={customer.email}><td><b>{customer.name}</b><small>{customer.email}</small></td><td>{customer.orders.length}</td><td>{customer.completedBooks}</td><td><div className="admin-loyalty-progress"><b>{customer.nextRewardProgress}/5</b><span><i style={{width:`${customer.nextRewardProgress*20}%`}}/></span></div></td><td>{customer.earnedCoupons} emitidos</td></tr>)}</tbody></table>{initialCustomers.length===0&&<p className="admin-empty">Aún no hay compras registradas.</p>}</section><div className="admin-customer-history"><h2>Historial de compras</h2>{initialCustomers.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(query.toLowerCase())).map(c=><section className="admin-panel" key={c.email}><div className="admin-panel-title"><div><h2>{c.name}</h2><p>{c.email}</p></div><span>{c.completedBooks} libros entregados</span></div><OrderTable orders={c.orders} onSelect={(id)=>{setSelected(id);setSection("Pedidos");}}/></section>)}</div></>}
        {section === "Cupones" && <><div className="admin-heading"><div><p className="admin-eyebrow">PROGRAMA DE LEALTAD</p><h1 className="editorial-serif">Cupones de recompensa</h1><p className="admin-muted">Se genera un cupón personal de 10% al completar cada cinco libros pagados y entregados.</p></div></div><section className="admin-panel admin-table-panel"><table className="admin-table"><thead><tr><th>CÓDIGO</th><th>CLIENTE</th><th>BENEFICIO</th><th>HITO</th><th>ESTADO</th></tr></thead><tbody>{initialCoupons.map(coupon=><tr key={coupon.id}><td><b>{coupon.code}</b></td><td>{coupon.email}</td><td>{coupon.percent}% de descuento</td><td>{coupon.milestone * 5} libros</td><td><span className={`admin-pill ${coupon.used?"gray":"green"}`}><i/>{coupon.used?"Canjeado":coupon.reservedOrderId?"En pedido":"Disponible"}</span></td></tr>)}</tbody></table>{initialCoupons.length===0&&<p className="admin-empty">Los cupones aparecerán aquí cuando un cliente complete su primer grupo de cinco libros entregados.</p>}</section></>}
        {section === "Reposición" && <><div className="admin-heading"><div><p className="admin-eyebrow">DEMANDA DEL CATÁLOGO</p><h1 className="editorial-serif">Solicitudes de reposición</h1><p className="admin-muted">Personas que pidieron aviso para títulos sin existencias.</p></div></div><section className="admin-panel admin-table-panel"><table className="admin-table"><thead><tr><th>TÍTULO</th><th>PERSONA</th><th>CORREO</th><th>FECHA</th><th>INTERÉS</th></tr></thead><tbody>{restockRequests.map((request)=><tr key={request.id}><td><b>{books.find(book=>book.id===request.bookId)?.title || "Título eliminado"}</b></td><td>{request.name}</td><td>{request.email}</td><td>{new Date(request.createdAt).toLocaleDateString("es-MX")}</td><td>{restockRequests.filter(item=>item.bookId===request.bookId).length} solicitudes</td></tr>)}</tbody></table>{restockRequests.length===0&&<p className="admin-empty">Todavía no hay solicitudes. Cuando alguien pida aviso desde el catálogo, aparecerá aquí.</p>}</section></>}
      </div>
    </main>
    {editing !== undefined && <BookEditor book={editing} onClose={()=>setEditing(undefined)} onSaved={(book)=>{setBooks(current=>editing ? current.map(item=>item.id===book.id?book:item) : [book,...current]);setEditing(undefined);setNotice("Ficha guardada correctamente.");}}/>}
  </div>;
}

function Stat({icon:Icon,label,value,note}:{icon:typeof Boxes;label:string;value:string;note:string}) { return <article className="admin-stat"><span className="admin-stat-icon"><Icon size={19}/></span><span className="admin-stat-label">{label}</span><b>{value}</b><small>{note}</small></article>; }

function OrderTable({orders,onSelect,selected}:{orders:AdminOrder[];onSelect:(id:string)=>void;selected?:string}) { return orders.length ? <div className="admin-order-table">{orders.map(order=><button key={order.id} className={`admin-order-row ${selected===order.id?"selected":""}`} onClick={()=>onSelect(order.id)}><span><b>{order.id}</b><small>{order.customer}</small></span><span>{new Date(`${order.date}T12:00:00`).toLocaleDateString("es-MX",{day:"numeric",month:"short"})}</span><span>{money(order.total)}</span><span className={`admin-pill ${order.status==="Entregado"?"green":order.status==="Enviado"?"blue":order.status==="Cancelado"?"gray":"amber"}`}><i/>{order.status}</span></button>)}</div> : <p className="admin-empty">No hay pedidos que coincidan.</p>; }

function OrderDetail({order,onSave}:{order:AdminOrder;onSave:(data:FormData)=>Promise<void>}) { const [busy,setBusy]=useState(false); return <section className="admin-panel admin-order-detail"><div className="admin-detail-head"><div><p className="admin-eyebrow">DETALLE DEL PEDIDO</p><h2>{order.id}</h2><p className="admin-muted">{order.customer} · {order.email}</p></div><span className={`admin-pill ${order.status==="Entregado"?"green":order.status==="Enviado"?"blue":"amber"}`}><i/>{order.status}</span></div><div className="admin-detail-meta"><div><small>FECHA</small><b>{new Date(`${order.date}T12:00:00`).toLocaleDateString("es-MX",{day:"numeric",month:"long",year:"numeric"})}</b></div><div><small>DIRECCIÓN DE ENTREGA</small><b>{order.address}</b></div></div><h3 className="admin-subheading">Artículos</h3><div className="admin-order-items">{order.items.map(item=><div key={item.bookId}><span><b>{item.title}</b><small>Cantidad: {item.quantity}</small></span><span>{money(item.unitPrice * item.quantity)}</span></div>)}</div><div className="admin-total"><span>Total del pedido</span><b>{money(order.total)}</b></div><form className="admin-order-form" action={async(data)=>{setBusy(true);await onSave(data);setBusy(false);}}><input type="hidden" name="id" value={order.id}/><h3 className="admin-subheading">Pago y envío</h3><label>Estado de pago<select name="paymentStatus" defaultValue={order.paymentStatus}>{(["Pendiente","Pagado","Reembolsado"] as PaymentStatus[]).map(s=><option key={s}>{s}</option>)}</select></label><label>Estado del pedido<select name="status" defaultValue={order.status}>{(["Pendiente","Procesando","Enviado","Entregado","Cancelado"] as OrderStatus[]).map(s=><option key={s}>{s}</option>)}</select></label><div className="admin-shipping-label"><Truck size={16}/> Información de envío</div><label>Paquetería<input name="carrier" placeholder="Ej. Estafeta, DHL, FedEx" defaultValue={order.carrier}/></label><label>Número de rastreo<input name="tracking" placeholder="Ingresa la guía de rastreo" defaultValue={order.tracking}/></label>{order.tracking&&<a className="admin-tracking-link" href={`https://www.google.com/search?q=${encodeURIComponent(`${order.carrier} rastreo ${order.tracking}`)}`} target="_blank" rel="noreferrer">Consultar rastreo <ExternalLink size={13}/></a>}<button className="admin-primary admin-save-order" disabled={busy}>{busy?"Guardando…":"Guardar cambios"}</button></form></section>; }

function BookEditor({book,onClose,onSaved}:{book:Book|null;onClose:()=>void;onSaved:(book:Book)=>void}) {
  const [busy,setBusy]=useState(false); const [uploading,setUploading]=useState(false); const [error,setError]=useState("");
  const [coverImage,setCoverImage]=useState(book?.coverImage||""); const [productImages,setProductImages]=useState<string[]>(book?.productImages||[]);
  async function upload(files:FileList|null, target:"cover"|"gallery") {
    if(!files?.length)return;
    const selected=Array.from(files).slice(0,target==="cover"?1:4-productImages.length);
    if(!selected.length){setError("La galería admite hasta 4 fotos.");return;}
    setUploading(true); setError("");
    try { const uploaded:string[]=[]; for(const file of selected){const form=new FormData();form.append("files",file);const response=await fetch("/api/admin/uploads",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||"No se pudieron subir las imágenes.");uploaded.push(...result.urls);}
      if(target==="cover")setCoverImage(uploaded[0]); else setProductImages(current=>[...current,...uploaded].slice(0,4));
    } catch(cause) { setError(cause instanceof Error?cause.message:"No se pudieron subir las imágenes."); }
    finally {setUploading(false);}
  }
  return <div className="admin-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="admin-modal"><div className="admin-modal-head"><div><p className="admin-eyebrow">FICHA DE CATÁLOGO</p><h2 className="editorial-serif">{book?"Editar libro":"Agregar libro"}</h2></div><button className="admin-icon-button" onClick={onClose}><X size={20}/></button></div>
    <form className="admin-book-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");const form=new FormData(e.currentTarget);const title=String(form.get("title"));const data={...(book?{id:book.id}:{}),title,slug:String(form.get("slug")||title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")),author:String(form.get("author")),publisher:String(form.get("publisher")),description:String(form.get("description")),price:Number(form.get("price")),year:Number(form.get("year")),stock:Number(form.get("stock")),available:Number(form.get("stock"))>0,isNew:form.has("isNew"),featured:form.has("featured"),coverImage,productImages,lifeStages:form.getAll("lifeStages") as LifeStage[],clinicalTopics:form.getAll("clinicalTopics") as ClinicalTopic[],theoreticalOrientations:form.getAll("theoreticalOrientations") as TheoreticalOrientation[]};try{const response=await fetch("/api/admin/books",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||"No se pudo guardar.");onSaved(result.book);}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo guardar.");}finally{setBusy(false);}}}>
      <div className="admin-image-upload-grid"><div className="admin-image-upload"><p className="admin-field-label">Portada principal</p><label className="admin-upload-control"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files,"cover")}/><span>{uploading?"Subiendo…":"Elegir portada"}</span></label>{coverImage?<div className="admin-image-preview"><img src={coverImage} alt="Vista previa de portada"/><button type="button" onClick={()=>setCoverImage("")}>Quitar portada</button></div>:<small>JPG, PNG o WebP · máximo 4 MB</small>}</div>
      <div className="admin-image-upload"><p className="admin-field-label">Fotos del producto <span>({productImages.length}/4)</span></p><label className="admin-upload-control"><input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={productImages.length>=4||uploading} onChange={e=>{upload(e.target.files,"gallery");e.currentTarget.value=""}}/><span>{uploading?"Subiendo…":"Añadir fotos"}</span></label><div className="admin-gallery-preview">{productImages.map((src,index)=><div key={src}><img src={src} alt={`Foto de producto ${index+1}`}/><button type="button" aria-label="Quitar foto" onClick={()=>setProductImages(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}</div><small>Hasta 4 fotos adicionales · máximo 4 MB cada una</small></div></div>
      <div className="admin-form-grid"><label className="span-two">Título<input name="title" required defaultValue={book?.title}/></label><label>Autor/a<input name="author" required defaultValue={book?.author}/></label><label>Editorial<input name="publisher" required defaultValue={book?.publisher}/></label><label>Precio (MXN)<input name="price" type="number" min="0" required defaultValue={book?.price}/></label><label>Año<input name="year" type="number" min="1000" max="2100" required defaultValue={book?.year}/></label><label>Existencias<input name="stock" type="number" min="0" required defaultValue={book?.stock ?? 0}/></label><label className="span-two">Descripción<textarea name="description" rows={3} required defaultValue={book?.description}/></label></div>
      <p className="admin-field-label">Etapas de vida</p><div className="admin-check-grid">{stages.map(value=><label key={value}><input type="checkbox" name="lifeStages" value={value} defaultChecked={book?.lifeStages.includes(value)}/> {value}</label>)}</div><p className="admin-field-label">Temas clínicos</p><div className="admin-check-grid">{topics.map(value=><label key={value}><input type="checkbox" name="clinicalTopics" value={value} defaultChecked={book?.clinicalTopics.includes(value)}/> {value}</label>)}</div><p className="admin-field-label">Corrientes</p><div className="admin-check-grid">{orientations.map(value=><label key={value}><input type="checkbox" name="theoreticalOrientations" value={value} defaultChecked={book?.theoreticalOrientations.includes(value)}/> {value}</label>)}</div><div className="admin-toggle-row"><label><input type="checkbox" name="isNew" defaultChecked={book?.isNew}/> Novedad</label><label><input type="checkbox" name="featured" defaultChecked={book?.featured}/> Destacado</label></div>
      {error&&<p className="admin-error" role="alert">{error}</p>}<div className="admin-modal-actions"><button type="button" className="admin-secondary" onClick={onClose}>Cancelar</button><button disabled={busy||uploading} className="admin-primary">{busy?"Guardando…":"Guardar ficha"}</button></div></form></section></div>;
}







