"use client";

import { useState } from "react";
import { LogOut, TicketPercent, UserRound } from "lucide-react";
import type { AdminOrder, RewardCoupon } from "@/lib/admin-data";

const money = (n: number) => new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN", maximumFractionDigits: 0 }).format(n);
type Account = { name: string; email: string; orders: AdminOrder[]; completedBooks: number; nextRewardProgress: number; coupons: RewardCoupon[] };

export default function CustomerAccountPanel({ account, error }: { account: Account | null; error?: string }) {
  const [register, setRegister] = useState(false);
  const message = error === "datos" ? "Revisa tus datos. La contraseña debe tener al menos 12 caracteres." : error === "registro" ? "No se pudo crear la cuenta. Tal vez ese correo ya está registrado." : error === "acceso" ? "Correo o contraseña incorrectos." : "";
  if (account) return <section className="customer-account"><header className="customer-account-head"><div><p className="admin-eyebrow">TU ESPACIO EN EL DIVÁN</p><h1 className="editorial-serif">Hola, {account.name}</h1><p>{account.email}</p></div><form action="/api/account/logout" method="post"><button className="customer-logout"><LogOut size={15}/> Cerrar sesión</button></form></header><div className="customer-reward"><TicketPercent size={21}/><div><b>Tu recompensa de lealtad</b><p>Por cada cinco libros pagados y entregados desbloqueas un cupón de 10%.</p><div className="customer-progress"><span><i style={{width:`${account.nextRewardProgress*20}%`}}/></span><small>{account.nextRewardProgress} de 5 libros para tu siguiente cupón</small></div></div></div><section className="customer-section"><h2 className="editorial-serif">Tus cupones</h2>{account.coupons.length ? <div className="customer-coupons">{account.coupons.map(c=><article key={c.id}><b>{c.code}</b><span>{c.percent}% de descuento</span><small>{c.used?"Canjeado":c.reservedOrderId?"En pedido":"Disponible"}</small></article>)}</div> : <p className="customer-empty">Cuando completes cinco libros entregados, tu cupón aparecerá aquí.</p>}</section><section className="customer-section"><h2 className="editorial-serif">Historial de compras</h2>{account.orders.length ? <div className="customer-orders">{account.orders.map(order=><article key={order.id}><div><b>{order.id}</b><small>{new Date(`${order.date}T12:00:00`).toLocaleDateString("es-MX",{day:"numeric",month:"long",year:"numeric"})} · {order.items.reduce((sum,item)=>sum+item.quantity,0)} libros</small></div><span className="customer-status">{order.status}</span><b>{money(order.total)}</b></article>)}</div> : <p className="customer-empty">Tus pedidos aparecerán aquí después de tu primera compra.</p>}</section></section>;
  return <section className="customer-login-card"><div className="customer-login-icon"><UserRound size={23}/></div><p className="admin-eyebrow">EL DIVÁN · MI CUENTA</p><h1 className="editorial-serif">{register?"Crear cuenta":"Bienvenido de vuelta"}</h1><p className="customer-login-copy">{register?"Crea tu cuenta para consultar pedidos y acumular recompensas.":"Inicia sesión para ver tus compras y recompensas."}</p>{message&&<p className="admin-error" role="alert">{message}</p>}<form action={register?"/api/account/register":"/api/account/login"} method="post" className="customer-form">{register&&<label>Nombre completo<input name="name" required minLength={2} maxLength={100} autoComplete="name"/></label>}<label>Correo electrónico<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>Contraseña<input name="password" type="password" required minLength={register?12:1} maxLength={200} autoComplete={register?"new-password":"current-password"}/>{register&&<small>Usa al menos 12 caracteres.</small>}</label><button className="admin-primary">{register?"Crear mi cuenta":"Iniciar sesión"}</button></form><button className="customer-mode-toggle" onClick={()=>setRegister(!register)}>{register?"Ya tengo una cuenta · Iniciar sesión":"¿Aún no tienes cuenta? · Crear cuenta"}</button></section>;
}

