import type { Metadata } from "next";
import LegalPage from "@/components/legal-page";
export const metadata: Metadata = { title: "Términos y condiciones | El Diván", description: "Condiciones para navegar y comprar en El Diván." };
export default function TermsPage() { return <LegalPage title="Términos y condiciones" intro="Condiciones para utilizar la tienda en línea de El Diván Mundo Psicoanalítico." sections={[
 {title:"Proveedor",paragraphs:["La tienda es operada por El Diván Mundo Psicoanalítico. Antes de publicar, el proveedor debe completar su nombre o razón social, domicilio y medios de contacto: [completar datos legales y de atención al cliente]."]},
 {title:"Cuenta y uso",paragraphs:["Al crear una cuenta, proporciona información vigente y protege tu contraseña. La cuenta es personal. El catálogo está dirigido a personas interesadas en libros; las descripciones editoriales son informativas y no sustituyen asesoría clínica, médica o profesional."]},
 {title:"Productos, precios y existencias",paragraphs:["Los precios se muestran en pesos mexicanos (MXN), salvo indicación distinta. Procuramos mantener fichas y existencias actualizadas; la disponibilidad puede cambiar hasta confirmar el pedido. Portadas y detalles de edición pueden variar según el ejemplar disponible.","Si detectamos un error material de precio o disponibilidad, te contactaremos para explicarlo y acordar cómo proceder antes de continuar con el cobro."]},
 {title:"Pedidos y pagos",paragraphs:["Al confirmar el carrito se registra una solicitud y se reservan temporalmente las existencias. Actualmente el pedido queda con pago pendiente y no se procesa un cobro en línea. No se considera pagado hasta que El Diván confirme el pago por un medio acordado.","Antes de cualquier cobro te informaremos el total, incluidos los cargos de envío aplicables, y el medio de pago. Cupones y promociones se sujetan a vigencia, requisitos, límites y condiciones publicados."]},
 {title:"Envíos",paragraphs:["La dirección de entrega debe ser completa y correcta. La paquetería, costo y plazo estimado dependen del destino y se comunicarán antes del despacho. Al enviar el pedido añadiremos la guía de rastreo disponible.","Los plazos son estimados y pueden variar por cobertura del transportista, días inhábiles o causas ajenas a la tienda. Para solicitar ayuda, utiliza los datos de contacto publicados."]},
 {title:"Cancelaciones, devoluciones y garantías",paragraphs:["Para cancelar o reportar un problema, comunícate indicando el número de pedido y el motivo. Revisaremos la solicitud según el estado del pedido y los derechos que reconoce la legislación de protección al consumidor. El proveedor debe completar y publicar las condiciones específicas de cambios, devoluciones, productos defectuosos y reembolsos antes de iniciar ventas."]},
 {title:"Lealtad",paragraphs:["Las recompensas dependen de las compras que cumplan las condiciones vigentes del programa. Cada cupón puede tener vigencia, límites y reglas de uso propios, que se informarán en la tienda."]},
 {title:"Propiedad intelectual y servicio",paragraphs:["La identidad, textos y diseño propios de la tienda pertenecen a El Diván o se utilizan con autorización. Las marcas y contenidos de terceros pertenecen a sus titulares. Podemos actualizar el catálogo, las funciones y estas condiciones; el servicio puede tener interrupciones técnicas."]},
 {title:"Legislación y contacto",paragraphs:["Estas condiciones se interpretan conforme a las leyes aplicables en México, sin limitar derechos irrenunciables de las personas consumidoras. Para dudas o reclamaciones: [completar correo, teléfono y domicilio de atención]."]}
]}/>; }
