import type { Metadata } from "next";
import LegalPage from "@/components/legal-page";
export const metadata: Metadata = { title: "Aviso de privacidad | El Diván", description: "Conoce cómo El Diván trata tus datos personales." };
export default function PrivacyNoticePage() { return <LegalPage title="Aviso de privacidad" intro="Este aviso describe el tratamiento de datos personales relacionado con las cuentas, compras y comunicaciones de El Diván." sections={[
 {title:"Responsable y contacto",paragraphs:["Responsable: El Diván Mundo Psicoanalítico, operado por [completar nombre o razón social de la persona responsable]. Domicilio: [completar domicilio]. Contacto para privacidad: [completar correo electrónico]. Estos datos deben completarse antes de publicar la tienda de forma definitiva."]},
 {title:"Datos que podemos tratar",bullets:["Cuenta: nombre, correo electrónico, fecha de registro y contraseña almacenada como hash.","Compra y entrega: libros, cantidades, importes, dirección proporcionada y estados de pago y envío.","Carrito: libros y cantidades asociados a la cuenta cuando inicias sesión.","Reposición: nombre, correo y título solicitado.","Boletín: nombre opcional, correo, fecha de autorización y estado de suscripción.","Datos técnicos mínimos de sesión mediante cookies necesarias y almacenamiento local del carrito."]},
 {title:"Finalidades",bullets:["Crear y administrar cuentas; procesar pedidos, reservar inventario y dar seguimiento a pagos y entregas.","Atender consultas, solicitudes de reposición y recompensas del programa de lealtad.","Registrar tu elección del boletín. Las novedades y promociones solo se enviarán con autorización expresa; actualmente los envíos automáticos están desactivados.","Mantener la seguridad de las sesiones y recordar el carrito en tu dispositivo."]},
 {title:"Transferencias y proveedores",paragraphs:["No vendemos tus datos personales. Podemos utilizar proveedores para alojar y mantener el sitio y, cuando se habiliten, para pagos y paquetería, compartiendo únicamente los datos necesarios para completar la operación solicitada. Actualizaremos este aviso cuando se definan los proveedores y transferencias aplicables."]},
 {title:"Conservación y protección",paragraphs:["Conservamos los datos durante el tiempo necesario para atender la finalidad que motivó su recopilación y cumplir obligaciones legales o defender derechos. Aplicamos medidas administrativas y técnicas razonables para protegerlos; ningún sistema conectado a internet puede prometer seguridad absoluta."]},
 {title:"Derechos ARCO y revocación",paragraphs:["Puedes solicitar acceso, rectificación, cancelación u oposición (derechos ARCO), así como revocar tu consentimiento cuando corresponda. Escribe a [completar correo de privacidad], indicando cómo localizar tus datos y qué derecho deseas ejercer. Podremos pedir información para verificar tu identidad y atenderemos la solicitud conforme a la legislación aplicable."]},
 {title:"Cambios",paragraphs:["Publicaremos las actualizaciones en esta página e indicaremos la fecha de revisión. Si un cambio requiere un nuevo consentimiento, lo solicitaremos por el medio correspondiente."]}
]}/>; }
