import type { Metadata } from "next";
import LegalPage from "@/components/legal-page";
export const metadata: Metadata = { title: "Política de cookies | El Diván", description: "Información sobre cookies y almacenamiento local utilizados por El Diván." };
export default function CookiePolicyPage() { return <LegalPage title="Política de cookies" intro="Te explicamos qué almacenamiento técnico utiliza este sitio y para qué sirve." sections={[
 {title:"Cookies necesarias",paragraphs:["El Diván utiliza cookies estrictamente necesarias para mantener la sesión de las cuentas de clientes y proteger el acceso al panel administrativo. La cookie de cliente puede durar hasta 14 días y la de administración hasta 8 horas, salvo que se cierre antes. Se configuran como HttpOnly y SameSite=Lax; en producción se transmiten únicamente por HTTPS."]},
 {title:"Carrito y preferencia en tu dispositivo",paragraphs:["El carrito se guarda en el almacenamiento local del navegador (localStorage) con la clave técnica eldivan-cart. No es una cookie. Permite conservar los libros agregados entre páginas y visitas desde el mismo navegador. Tu elección del banner se guarda también localmente como eldivan-cookie-choice para recordar si aceptaste las cookies necesarias o rechazaste las opcionales. Puedes borrar ambos datos desde la configuración de almacenamiento del navegador."]},
 {title:"Analítica y publicidad",paragraphs:["Actualmente no configuramos cookies propias para analítica, publicidad conductual ni seguimiento entre sitios. Si esto cambia, actualizaremos esta política antes de activar tecnologías no esenciales."]},
 {title:"Servicios externos y controles",paragraphs:["Los sitios externos enlazados desde El Diván, como redes sociales, pueden usar sus propias tecnologías conforme a sus políticas; no controlamos su funcionamiento. Puedes revisar o borrar cookies y datos del sitio desde tu navegador. Si bloqueas las cookies necesarias, el inicio de sesión puede dejar de funcionar."]}
]}/>; }
